#!/usr/bin/bash

build() {
  if [[ -r /etc/initcpio/message ]]; then
    add_file /etc/initcpio/message /message
    add_runscript
  fi
}

help() {
  echo "This hook displays a message. The message can be set by modifying"
  echo "the file at /etc/initcpio/message."
}
